In [3]:
import pandas as pd

# Task 1

In [5]:
df_director = pd.read_csv('disney-director.csv')

df_director

    index                                    name             director
0       0         Snow White and the Seven Dwarfs           David Hand
1       1                               Pinocchio       Ben Sharpsteen
2       2                                Fantasia         full credits
3       3                                   Dumbo       Ben Sharpsteen
4       4                                   Bambi           David Hand
5       5                          Saludos Amigos          Jack Kinney
6       6                    The Three Caballeros      Norman Ferguson
7       7                         Make Mine Music          Jack Kinney
8       8                      Fun and Fancy Free          Jack Kinney
9       9                             Melody Time       Clyde Geronimi
10     10  The Adventures of Ichabod and Mr. Toad          Jack Kinney
11     11                              Cinderella      Wilfred Jackson
12     12                     Alice in Wonderland       Clyde Geronimi
13     13                               Peter Pan       Hamilton Luske
14     14                      Lady and the Tramp       Hamilton Luske
15     15                         Sleeping Beauty       Clyde Geronimi
16     16                          101 Dalmatians  Wolfgang Reitherman
17     17                  The Sword in the Stone  Wolfgang Reitherman
18     18                         The Jungle Book  Wolfgang Reitherman
19     19                          The Aristocats  Wolfgang Reitherman
20     20                              Robin Hood  Wolfgang Reitherman
21     21  The Many Adventures of Winnie the Pooh  Wolfgang Reitherman
22     22                            The Rescuers  Wolfgang Reitherman
23     23                   The Fox and the Hound          Art Stevens
24     24                      The Black Cauldron           Ted Berman
25     25               The Great Mouse Detective         Ron Clements
26     26                        Oliver & Company      George Scribner
27     27                      The Little Mermaid         Ron Clements
28     28                 The Rescuers Down Under         Mike Gabriel
29     29                    Beauty and the Beast       Gary Trousdale
30     30                                 Aladdin         Ron Clements
31     31                           The Lion King         Roger Allers
32     32                              Pocahontas         Mike Gabriel
33     33             The Hunchback of Notre Dame       Gary Trousdale
34     34                                Hercules         Ron Clements
35     35                                   Mulan           Barry Cook
36     36                                  Tarzan           Chris Buck
37     37                           Fantasia 2000         full credits
38     38                                Dinosaur         Ralph Zondag
39     39                The Emperor's New Groove          Mark Dindal
40     40               Atlantis: The Lost Empire       Gary Trousdale
41     41                           Lilo & Stitch        Chris Sanders
42     42                         Treasure Planet         Ron Clements
43     43                            Brother Bear        Robert Walker
44     44                       Home on the Range            Will Finn
45     45                          Chicken Little          Mark Dindal
46     46                      Meet the Robinsons  Stephen J. Anderson
47     47                                    Bolt       Chris Williams
48     48               The Princess and the Frog         Ron Clements
49     49                                 Tangled         Nathan Greno
50     50                         Winnie the Pooh  Stephen J. Anderson
51     51                          Wreck-It Ralph           Rich Moore
52     52                                  Frozen           Chris Buck
53     53                              Big Hero 6             Don Hall
54     54                                Zootopia         Byron Howard
55     55                                   Moana         Ron Clements

In [7]:
# Counting titles per director
titles_per_director = df_director.groupby('director')['name'].count().reset_index(name='number_of_titles')

# Ordering the table from highest to lowest number of titles directed
titles_per_director_sorted = titles_per_director.sort_values('number_of_titles', ascending=False)

titles_per_director_sorted

               director  number_of_titles
27  Wolfgang Reitherman                 7
22         Ron Clements                 7
13          Jack Kinney                 4
10       Gary Trousdale                 3
7        Clyde Geronimi                 3
14          Mark Dindal                 2
23  Stephen J. Anderson                 2
15         Mike Gabriel                 2
12       Hamilton Luske                 2
28         full credits                 2
8            David Hand                 2
2        Ben Sharpsteen                 2
4            Chris Buck                 2
9              Don Hall                 1
20        Robert Walker                 1
26            Will Finn                 1
25      Wilfred Jackson                 1
24           Ted Berman                 1
3          Byron Howard                 1
21         Roger Allers                 1
19           Rich Moore                 1
11      George Scribner                 1
18         Ralph Zondag                 1
17      Norman Ferguson                 1
16         Nathan Greno                 1
5         Chris Sanders                 1
1            Barry Cook                 1
6        Chris Williams                 1
0           Art Stevens                 1

# Task 2